name: learn env
on: [push, workflow_dispatch]
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          echo "This is a test"
          exit 0 # Simulate failure
  run-always:
    runs-on: ubuntu-latest
    if: always()
    needs: fail
    steps:
      - name: Run script
        run: |
          sleep 5
          echo "This is a test"
          exit 0 # Simulate success

