on: [push, workflow_dispatch]
jobs:
  gentrate_output:
    runs-on: ubunu-latest
    outputs:
      output1: ${{steps.step1.outputs.output1}}
    steps:
      - name: step1
        id: step1
        run: |
          echo "output1=Hello World" >> $GITHUB_OUTPUT
