name: learn env
on: [push, workflow_dispatch]
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          echo "This is a test"
          exit 1 # Simulate failure
  

