name: First workflow
on: 
  - workflow_dispatch
  - push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: setp one
        run: echo 'hello world'
      - name: step two
        run: echo 'hello world 2'
  secondjob:
    runs-on: windows-latest
    needs: firstjob
    
    steps:
      - name: step 1
        shell: pwsh
        run: echo 'hello '
