name: learn env
on:
  workflow_dispatch: 
    inputs:
      envroinment:
        type: environment


jobs:
  show-env:
    environment: ${{inputs.envroinment}}
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(vars)}}'
  