name: Print ENV local variables values
on: push
jobs:
  deploy-to-dev:
    environment: Developement
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variables 
        run: | 
         echo "Repository Variable: ${{ vars.USERNAME }}"  
  deploy-to-staging:
    environment: staging
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variables 
        run: | 
         echo "Repository Variable: ${{ vars.USERNAME }}"
  deploy-to-prod:
    environment: production
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    steps:
      - name: Print Repository Variables 
        run: | 
         echo "Repository Variable: ${{ vars.USERNAME }}"