on: [push, workflow_dispatch]
name: Learn GitHub Actions
concurrency: learn-github-actions
jobs:
  gentrate_output:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.output1}}
    steps:
      - name: step1
        id: step1
        run: |
          sleep 5
          echo "output1=Hello World" >> $GITHUB_OUTPUT
  use_output:
    runs-on: ubuntu-latest
    needs: gentrate_output
    steps:
      - name: step2
        id: step2
        run: |
          echo "output1=${{needs.gentrate_output.outputs.output1}}"  