name: learn env
on:
  workflow_dispatch: 
    inputs:
      envroinment:
        type: environment

jobs:
  show-env:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(vars)}}'
  