name: learn env
on: [push, workflow_dispatch]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run java
        run: |
          echo "Hello World"
          javac Main.java
          java Main