name: Learn martix startegy
on: 
  - push
  - workflow_dispatch
jobs:
  Matrix_job:
    strategy:
      matrix:
        os: [ubuntu-latest, window-latest, mac-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: running on ${{matrix.os}}
        run: ls -l