name: learn env
on: [push, workflow_dispatch]
jobs:
  fail:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          echo "This is a test"
          exit 1 # Simulate failure
  run-always:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          sleep 5
          echo "This is a test"
          exit 0 # Simulate success

