name: learn artifact
on:
  push:
  workflow_dispatch:
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "This is a test file" > test.txt
      - name: add to artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: test.txt
          