name: learn github actions
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: list files
        run: |
          echo "List of files in the repository:"
          ls -al

  