name: learn env
on:
  workflow_dispatch: 
    inputs:
      envroinment:
        type: environment
env:
  ENV_NAME: mairu

jobs:
  show-env:
    environment: ${{ inputs.envroinment}}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{env.ENV_NAME}}
  