name: Print Repository Variables and Secrets

on:
  push:
    branches:
      - main

jobs:
  print-vars-and-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variables 
        run: |
         echo "Repository Variable: ${{ vars.USERNAME }}"

      - name: Print Repository Secret
        run: |
          echo "Repository Secret: ${{ secrets.USERNAME }}" 