name: learn env
on: [push, workflow_dispatch]
env:
  javatest: 'Hey its working in github actions'
jobs:
  install-dependencies:
    env:
      javatest: 'from job'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run java
        env:
          javatest: 'from step'
        run: |
          javac Main.java
          java Main