name: Print Repository Variables and Secrets

on:
  push:
    branches:
      - main

jobs:
  print-vars-and-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variables 
        env:
          REPO_VAR: ${{ vars.VARIABLE1 }}
        run: |
         echo "Repository Variable: ${{ vars.VARIABLE1 }}"

      - name: Print Repository Secret
        env:
          SECRET_VAR: ${{ secrets.SECRET1 }}
        run: |
          echo "Repository Secret: ${{ secrets.SECRET1 }}" 