name: learn artifact
on:
  push:
  workflow_dispatch:
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "This is a test file" > test.txt
      - name: add to artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: test.txt
  use-file:
    runs-on: ubuntu-latest
    needs: create-file
    steps:
      - name: list files
        run: ls -al
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file
      - name: list files
        run: ls -al
      - name: Use file
        run: |
          cat test.txt