on:
  push:
  workflow_dispatch:
jobs:
  genrerate-output:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.step1.outputs.test }}
    steps:
      - name: step 1
        id: step1
        run: echo "test=Hello World" >> $GITHUB_OUTPUTS
  use-output:
    runs-on: ubuntu-latest
    needs: genrerate-output
    steps:
      - name: step 2
        run: echo "${{ needs.genrerate-output.outputs.test }}"
    