name: learn env
on: [push, workflow_dispatch]
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        id: step1
        run: |
          echo "This is a test"
          exit 0 # Simulate failure
      - name: step 2
        if: failure() && steps.step1.outcome == 'failure'
        run: |
          echo "Step 1 failed, so this step will run."
  run-fail-fails:
    runs-on: ubuntu-latest
    needs: fail
    if: always() && needs.fail.result == 'failure'
    steps:
      - name: Run script
        run: |
          sleep 5
          echo "This is a test"
          exit 0 # Simulate success

