name: First workflow
on: [workflow_dispatch,push]

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name : say hello
        run: echo "hello world"
      - name : print context
        run : echo "${{toJSON(github.event)}}"
  signOff:
    runs-on: ubuntu-18.04
    steps:
      - name : say goodbyeeee
        run : echo "Good bye....."
