name: First workflow
on: [workflow_dispatch,push]

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name : say hello
        run: echo "hello world"
  working:
    runs-on: ubuntu-latest
    steps:
      - name : do job
        run : echo "I am working ....."
  signOff:
    runs-on: ubuntu-latest
    needs: [Greeting,working]
    steps:
      - name : say goodbyeeee
        run : echo "Good bye....."
  goToHome:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name : say goodbyeeee
        run : echo "Good bye....."

