name: First workflow
on:
  workflow_dispatch
  pull_request:
    branchs:
      - main

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: test intendation
        run: echo "intendation worinkng "
      - name : say hello
        run: echo "hello world"
  working:
    runs-on: ubuntu-latest
    needs: Greeting
    steps:
      - name : do job
        run : echo "I am working ....."
  signOff:
    runs-on: ubuntu-latest
    needs: [working]
    steps:
      - name : say goodbyeeee
        run : echo "Good bye....."
  goToHome:
    runs-on: ubuntu-latest
    needs: [signOff]
    steps:
      - name : say goodbyeeee
        run : echo "Good bye....."

